kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: chivalry-local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      name: chivalry-data